functionsDirectory = "/Users/jessicahall/fit-finder/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/jessicahall/fit-finder"
publishOrigin = "default"
functions = "/Users/jessicahall/fit-finder/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]